"""
Seed exercise fixtures into the exercises table.
Run with:  python -m app.seed  (from the backend/ directory)
"""

from .database import SessionLocal
from . import models

EXERCISES = [
    # Push
    {"id": "bench",       "name": "Bench Press",           "category": "Push",      "type": "strength", "description": "Classic flat barbell press for the chest, front delts, and triceps.", "primary_muscles": ["lower_pec", "upper_pec"],                              "secondary_muscles": ["front_delt", "tricep_lat", "tricep_med"]},
    {"id": "incline_db",  "name": "Incline DB Press",      "category": "Push",      "type": "strength", "description": "Upper-chest focused press on an inclined bench using dumbbells for a deeper stretch and free range of motion.", "primary_muscles": ["upper_pec", "front_delt"],                             "secondary_muscles": ["tricep_lat", "tricep_med"]},
    {"id": "incline_bar", "name": "Incline Bar Press",     "category": "Push",      "type": "strength", "description": "Barbell version of the incline press, allowing heavier loading on the upper pec and front deltoid.", "primary_muscles": ["upper_pec", "front_delt"],                             "secondary_muscles": ["tricep_lat", "tricep_med"]},
    {"id": "decline",     "name": "Decline Press",         "category": "Push",      "type": "strength", "description": "Bench press performed on a head-down incline to bias the lower portion of the chest.", "primary_muscles": ["lower_pec"],                                           "secondary_muscles": ["tricep_lat", "front_delt"]},
    {"id": "cable_fly",   "name": "Cable Fly",             "category": "Push",      "type": "strength", "description": "Standing isolation movement that sweeps the arms together against constant cable tension to squeeze the chest.", "primary_muscles": ["lower_pec", "upper_pec"],                              "secondary_muscles": ["front_delt"]},
    {"id": "pec_deck",    "name": "Pec Deck",              "category": "Push",      "type": "strength", "description": "Machine fly that locks the elbows in place so all the work goes into the chest contraction.", "primary_muscles": ["lower_pec", "upper_pec"],                              "secondary_muscles": ["front_delt"]},
    {"id": "dips",        "name": "Dips",                  "category": "Push",      "type": "strength", "description": "Bodyweight press between parallel bars; lean forward for chest emphasis, stay vertical for triceps.", "primary_muscles": ["lower_pec", "tricep_long"],                            "secondary_muscles": ["front_delt", "tricep_lat"]},
    {"id": "skull",       "name": "Skull Crushers",        "category": "Push",      "type": "strength", "description": "Lying tricep extension where an EZ-bar is lowered toward the forehead to isolate the elbow extensors.", "primary_muscles": ["tricep_long", "tricep_lat"],                           "secondary_muscles": ["tricep_med"]},
    {"id": "cgbench",     "name": "Close-Grip Bench",      "category": "Push",      "type": "strength", "description": "Bench press with a narrower grip and tucked elbows to shift load onto the triceps.", "primary_muscles": ["tricep_lat", "tricep_med"],                            "secondary_muscles": ["lower_pec", "front_delt"]},
    {"id": "tri_push",    "name": "Tricep Pushdown",       "category": "Push",      "type": "strength", "description": "Cable extension where the upper arms stay pinned and only the forearms move to lock out the elbow.", "primary_muscles": ["tricep_lat", "tricep_med"],                            "secondary_muscles": ["tricep_long"]},
    {"id": "tri_oh",      "name": "Overhead Tricep Ext.",  "category": "Push",      "type": "strength", "description": "Overhead extension that puts the triceps in a stretched position for extra long-head emphasis.", "primary_muscles": ["tricep_long"],                                         "secondary_muscles": ["tricep_lat", "tricep_med"]},
    {"id": "ohp",         "name": "Overhead Press",        "category": "Push",      "type": "strength", "description": "Standing barbell press from the front rack straight overhead — the staple shoulder strength lift.", "primary_muscles": ["front_delt", "side_delt"],                             "secondary_muscles": ["upper_pec", "tricep_lat", "tricep_med", "upper_trap"]},
    {"id": "db_press",    "name": "DB Shoulder Press",     "category": "Push",      "type": "strength", "description": "Seated dumbbell overhead press; freer path than a barbell and easier on the shoulders.", "primary_muscles": ["front_delt", "upper_pec"],                             "secondary_muscles": ["tricep_lat", "tricep_med"]},
    {"id": "arnold",      "name": "Arnold Press",          "category": "Push",      "type": "strength", "description": "Seated press that rotates the palms from facing-in to facing-out to hit every head of the deltoid.", "primary_muscles": ["front_delt", "side_delt"],                             "secondary_muscles": ["upper_pec", "tricep_lat"]},
    # Pull
    {"id": "lat_pd",       "name": "Lat Pulldown",         "category": "Pull",      "type": "strength", "description": "Seated cable pull-down to the upper chest that mimics a pull-up with adjustable resistance.", "primary_muscles": ["upper_lat", "lower_lat"],                              "secondary_muscles": ["teres_major", "bicep_long", "bicep_short", "rear_delt"]},
    {"id": "lat_pd_wide",  "name": "Wide-Grip Pulldown",   "category": "Pull",      "type": "strength", "description": "Pulldown with a wide overhand grip that biases the upper lats and teres major.", "primary_muscles": ["upper_lat"],                                           "secondary_muscles": ["lower_lat", "teres_major", "rear_delt"]},
    {"id": "lat_pd_close", "name": "Close-Grip Pulldown",  "category": "Pull",      "type": "strength", "description": "Pulldown with a neutral close grip that drives the elbows back for thicker lat development.", "primary_muscles": ["lower_lat", "teres_major"],                            "secondary_muscles": ["upper_lat", "bicep_long"]},
    {"id": "pullups",      "name": "Pull-ups",             "category": "Pull",      "type": "strength", "description": "Bodyweight pull from a dead hang to chin-over-bar — the king of vertical back movements.", "primary_muscles": ["upper_lat", "lower_lat"],                              "secondary_muscles": ["teres_major", "bicep_long", "rear_delt"]},
    {"id": "sa_pulldown",  "name": "Single-Arm Pulldown",  "category": "Pull",      "type": "strength", "description": "Unilateral cable pulldown that adds a torso rotation for deeper lat contraction.", "primary_muscles": ["upper_lat", "teres_major"],                            "secondary_muscles": ["lower_lat", "bicep_long"]},
    {"id": "tbar",         "name": "T-Bar Row",            "category": "Pull",      "type": "strength", "description": "Landmine row using a neutral grip handle for heavy, supported pulling.", "primary_muscles": ["lower_lat", "rhomboid"],                               "secondary_muscles": ["upper_lat", "teres_major", "bicep_short", "rear_delt"]},
    {"id": "bb_row",       "name": "Barbell Row",          "category": "Pull",      "type": "strength", "description": "Bent-over barbell row that builds total back thickness while drilling hip hinge stability.", "primary_muscles": ["lower_lat", "rhomboid", "lower_trap"],                 "secondary_muscles": ["upper_lat", "teres_major", "bicep_long", "rear_delt", "erector"]},
    {"id": "db_row",       "name": "DB Row",               "category": "Pull",      "type": "strength", "description": "One-arm dumbbell row supported on a bench for a long range of motion and squeezed back.", "primary_muscles": ["lower_lat", "teres_major"],                            "secondary_muscles": ["rhomboid", "upper_lat", "bicep_long", "rear_delt"]},
    {"id": "meadows",      "name": "Meadows Row",          "category": "Pull",      "type": "strength", "description": "Single-arm landmine row with a slight torso twist for an extreme peak contraction.", "primary_muscles": ["lower_lat", "teres_major"],                            "secondary_muscles": ["rhomboid", "upper_lat", "bicep_long"]},
    {"id": "cs_row",       "name": "Cable Seated Row",     "category": "Pull",      "type": "strength", "description": "Seated cable row to the lower abs that targets the mid-back retractors.", "primary_muscles": ["rhomboid", "lower_trap"],                              "secondary_muscles": ["lower_lat", "rear_delt", "bicep_short"]},
    {"id": "cable_row",    "name": "Cable Row",            "category": "Pull",      "type": "strength", "description": "Cable row variant with a wider, more lat-driven pull and a long stretch on the return.", "primary_muscles": ["lower_lat", "rhomboid"],                               "secondary_muscles": ["lower_trap", "bicep_long", "rear_delt"]},
    {"id": "face_pull",    "name": "Face Pull",            "category": "Pull",      "type": "strength", "description": "Rope pull to the face that hammers rear delts, external rotators, and mid-traps.", "primary_muscles": ["rear_delt", "lower_trap"],                             "secondary_muscles": ["rhomboid", "side_delt"]},
    {"id": "rev_fly",      "name": "Reverse Fly",          "category": "Pull",      "type": "strength", "description": "Bent-over rear delt fly with dumbbells for posture and shoulder balance.", "primary_muscles": ["rear_delt", "rhomboid"],                               "secondary_muscles": ["lower_trap", "side_delt"]},
    {"id": "bb_curl",      "name": "Barbell Curl",         "category": "Pull",      "type": "strength", "description": "Standing barbell curl — the foundational bicep mass builder.", "primary_muscles": ["bicep_long", "bicep_short"],                           "secondary_muscles": ["brachialis", "forearm"]},
    {"id": "db_curl",      "name": "DB Curl",              "category": "Pull",      "type": "strength", "description": "Dumbbell curl with a supinating wrist for fuller bicep contraction.", "primary_muscles": ["bicep_long", "bicep_short"],                           "secondary_muscles": ["brachialis", "forearm"]},
    {"id": "hammer",       "name": "Hammer Curl",          "category": "Pull",      "type": "strength", "description": "Neutral-grip dumbbell curl that loads the brachialis and forearms.", "primary_muscles": ["brachialis", "bicep_long"],                            "secondary_muscles": ["forearm"]},
    {"id": "preacher",     "name": "Preacher Curl",        "category": "Pull",      "type": "strength", "description": "Curl over a preacher pad that fixes the elbows for strict bicep loading.", "primary_muscles": ["bicep_short", "bicep_long"],                           "secondary_muscles": ["brachialis"]},
    {"id": "incline_curl", "name": "Incline DB Curl",      "category": "Pull",      "type": "strength", "description": "Lying-back dumbbell curl that hangs the arms behind the body to stretch the long head of the bicep.", "primary_muscles": ["bicep_long"],                                          "secondary_muscles": ["bicep_short", "brachialis"]},
    # Shoulders
    {"id": "lat_raise",   "name": "Lateral Raise",         "category": "Shoulders", "type": "strength", "description": "Standing dumbbell raise to the side — the go-to medial deltoid isolation lift.", "primary_muscles": ["side_delt"],                                           "secondary_muscles": ["upper_trap", "front_delt"]},
    {"id": "cable_lat",   "name": "Cable Lateral Raise",   "category": "Shoulders", "type": "strength", "description": "Single-arm cable lateral raise with constant tension across the whole range of motion.", "primary_muscles": ["side_delt"],                                           "secondary_muscles": ["upper_trap"]},
    {"id": "front_raise", "name": "Front Raise",           "category": "Shoulders", "type": "strength", "description": "Straight-arm raise of a dumbbell or plate to the front, isolating the anterior deltoid.", "primary_muscles": ["front_delt"],                                          "secondary_muscles": ["side_delt", "upper_pec"]},
    {"id": "upright_row", "name": "Upright Row",           "category": "Shoulders", "type": "strength", "description": "Vertical row from the thighs to the upper chest, lifting with the elbows for side delts and traps.", "primary_muscles": ["side_delt", "upper_trap"],                             "secondary_muscles": ["front_delt", "bicep_long"]},
    {"id": "shrug",       "name": "Barbell Shrug",         "category": "Shoulders", "type": "strength", "description": "Heavy straight-up barbell shrug to build the upper trapezius.", "primary_muscles": ["upper_trap"],                                          "secondary_muscles": ["lower_trap"]},
    {"id": "db_shrug",    "name": "DB Shrug",              "category": "Shoulders", "type": "strength", "description": "Shrug variant with dumbbells at the sides for a longer trap range.", "primary_muscles": ["upper_trap"],                                          "secondary_muscles": ["lower_trap"]},
    # Legs
    {"id": "squat",       "name": "Back Squat",            "category": "Legs",      "type": "strength", "description": "The fundamental lower-body strength lift — barbell on the traps, sit down between the hips, drive up.", "primary_muscles": ["quad_rf", "quad_vl", "quad_vmo", "glute_max"],         "secondary_muscles": ["ham_bf", "ham_semi", "adductor", "erector"]},
    {"id": "front_sq",    "name": "Front Squat",           "category": "Legs",      "type": "strength", "description": "Front-racked squat that forces a vertical torso and emphasises the quads.", "primary_muscles": ["quad_rf", "quad_vmo"],                                 "secondary_muscles": ["quad_vl", "glute_max", "erector"]},
    {"id": "hack_sq",     "name": "Hack Squat",            "category": "Legs",      "type": "strength", "description": "Machine squat with the shoulders supported, allowing heavy, knees-forward quad work.", "primary_muscles": ["quad_rf", "quad_vl", "quad_vmo"],                     "secondary_muscles": ["glute_max", "ham_bf"]},
    {"id": "leg_press",   "name": "Leg Press",             "category": "Legs",      "type": "strength", "description": "Seated machine press that lets you load heavy quad and glute work without spinal compression.", "primary_muscles": ["quad_vl", "quad_rf", "glute_max"],                    "secondary_muscles": ["quad_vmo", "ham_bf", "adductor"]},
    {"id": "leg_press_1", "name": "High-Foot Leg Press",   "category": "Legs",      "type": "strength", "description": "Leg press variant with feet placed high on the platform to bias the glutes and hamstrings.", "primary_muscles": ["quad_vmo", "quad_rf"],                                 "secondary_muscles": ["quad_vl", "glute_max"]},
    {"id": "bulg_split",  "name": "Bulgarian Split Squat", "category": "Legs",      "type": "strength", "description": "Single-leg squat with the back foot elevated for deep glute and quad stretch under load.", "primary_muscles": ["quad_rf", "glute_max"],                               "secondary_muscles": ["quad_vl", "quad_vmo", "ham_bf", "adductor"]},
    {"id": "lunges",      "name": "Lunges",                "category": "Legs",      "type": "strength", "description": "Long step forward and lower the back knee — unilateral leg builder that trains balance and stability.", "primary_muscles": ["quad_rf", "glute_max"],                               "secondary_muscles": ["quad_vl", "ham_bf", "adductor"]},
    {"id": "step_up",     "name": "Step-Up",               "category": "Legs",      "type": "strength", "description": "Step onto a box driving through the front heel — single-leg power and balance training.", "primary_muscles": ["quad_rf", "glute_max"],                               "secondary_muscles": ["quad_vl", "ham_bf"]},
    {"id": "rdl",         "name": "Romanian Deadlift",     "category": "Legs",      "type": "strength", "description": "Hip-hinge deadlift with soft knees that loads the hamstrings and glutes through their full stretch.", "primary_muscles": ["ham_bf", "ham_semi", "glute_max"],                    "secondary_muscles": ["erector", "adductor", "gastroc"]},
    {"id": "dead",        "name": "Deadlift",              "category": "Legs",      "type": "strength", "description": "The conventional barbell deadlift — pull from the floor to a full hip lockout.", "primary_muscles": ["ham_bf", "ham_semi", "glute_max", "erector"],         "secondary_muscles": ["quad_vl", "adductor", "upper_trap", "lower_lat"]},
    {"id": "sdl",         "name": "Stiff-Leg Deadlift",    "category": "Legs",      "type": "strength", "description": "Stricter-knee deadlift variant that maximises hamstring stretch and loading.", "primary_muscles": ["ham_bf", "ham_semi"],                                  "secondary_muscles": ["glute_max", "erector"]},
    {"id": "good_morn",   "name": "Good Morning",          "category": "Legs",      "type": "strength", "description": "Bar-on-back hip hinge that drills the posterior chain and back-flat technique with lighter weights.", "primary_muscles": ["ham_bf", "erector"],                                   "secondary_muscles": ["glute_max", "ham_semi"]},
    {"id": "hip_thrust",  "name": "Hip Thrust",            "category": "Legs",      "type": "strength", "description": "Bench-supported hip extension with a barbell across the hips — the prime glute lift.", "primary_muscles": ["glute_max", "glute_med"],                              "secondary_muscles": ["ham_bf", "ham_semi", "adductor"]},
    {"id": "leg_curl",    "name": "Lying Leg Curl",        "category": "Legs",      "type": "strength", "description": "Prone machine curl that isolates the hamstrings via knee flexion.", "primary_muscles": ["ham_bf", "ham_semi"],                                  "secondary_muscles": ["gastroc"]},
    {"id": "leg_curl_s",  "name": "Seated Leg Curl",       "category": "Legs",      "type": "strength", "description": "Seated machine variant that biases the semitendinosus/semimembranosus through a longer hip-flexed stretch.", "primary_muscles": ["ham_semi", "ham_bf"],                                  "secondary_muscles": ["gastroc"]},
    {"id": "leg_ext",     "name": "Leg Extension",         "category": "Legs",      "type": "strength", "description": "Seated machine quad isolation — extend the knee against the pad for a top-end squeeze.", "primary_muscles": ["quad_rf", "quad_vl", "quad_vmo"],                     "secondary_muscles": []},
    {"id": "calf_raise",  "name": "Standing Calf Raise",   "category": "Legs",      "type": "strength", "description": "Standing heel raise with straight legs to load the gastrocnemius.", "primary_muscles": ["gastroc"],                                             "secondary_muscles": ["soleus"]},
    {"id": "calf_seat",   "name": "Seated Calf Raise",     "category": "Legs",      "type": "strength", "description": "Seated calf raise with bent knees that biases the soleus.", "primary_muscles": ["soleus"],                                              "secondary_muscles": ["gastroc"]},
    # Core
    {"id": "w_situp",      "name": "Weighted Sit-up",      "category": "Core",      "type": "strength", "description": "Anchored sit-up holding a weight at the chest for direct rectus abdominis loading.", "primary_muscles": ["upper_abs", "lower_abs"],                              "secondary_muscles": ["oblique"]},
    {"id": "roman",        "name": "Back Extension",       "category": "Core",      "type": "strength", "description": "Hip-pinned extension on a roman chair that trains the spinal erectors and glutes.", "primary_muscles": ["erector"],                                             "secondary_muscles": ["glute_max", "ham_bf"]},
    {"id": "w_roman",      "name": "Oblique Ext.",         "category": "Core",      "type": "strength", "description": "Side-bend extension with a plate hugged to the chest to load the obliques as well as the erectors.", "primary_muscles": ["erector", "oblique"],                                  "secondary_muscles": ["glute_max"]},
    {"id": "cable_crunch", "name": "Cable Crunch",         "category": "Core",      "type": "strength", "description": "Kneeling rope crunch that rounds the spine against cable resistance for heavy ab work.", "primary_muscles": ["upper_abs", "lower_abs"],                              "secondary_muscles": ["oblique"]},
    {"id": "ab_wheel",     "name": "Ab Wheel",             "category": "Core",      "type": "strength", "description": "Bodyweight rollout that demands a braced core — advanced anterior-chain conditioner.", "primary_muscles": ["upper_abs", "lower_abs"],                              "secondary_muscles": ["oblique", "erector"]},
    {"id": "hanging_lr",   "name": "Hanging Leg Raise",    "category": "Core",      "type": "strength", "description": "Strict leg raise from a dead hang — gold standard for the lower abdominals.", "primary_muscles": ["lower_abs", "oblique"],                                "secondary_muscles": ["upper_abs"]},
    {"id": "dragon",       "name": "Dragon Flag",          "category": "Core",      "type": "strength", "description": "Advanced eccentric core hold (Bruce Lee staple) that lowers a straight body from vertical under full tension.", "primary_muscles": ["upper_abs", "lower_abs", "oblique"],                  "secondary_muscles": ["erector"]},
    {"id": "pallof",       "name": "Pallof Press",         "category": "Core",      "type": "strength", "description": "Anti-rotation cable press that trains the obliques to resist torque rather than create it.", "primary_muscles": ["oblique"],                                             "secondary_muscles": ["upper_abs", "lower_abs"]},
    {"id": "ghd",          "name": "GHD Sit-up",           "category": "Core",      "type": "strength", "description": "Full-range sit-up on a glute-ham developer pad — high demand on the entire trunk.", "primary_muscles": ["erector", "glute_max"],                                "secondary_muscles": ["ham_bf", "upper_abs"]},
    {"id": "plank",        "name": "Plank",                "category": "Core",      "type": "timed",    "description": "Static front hold on the forearms that builds isometric core endurance and bracing.", "primary_muscles": ["upper_abs", "lower_abs"],                              "secondary_muscles": ["oblique", "erector"]},
    {"id": "side_plank",   "name": "Side Plank",           "category": "Core",      "type": "timed",    "description": "Lateral isometric hold on one elbow that targets the obliques and hip stabilisers.", "primary_muscles": ["oblique"],                                             "secondary_muscles": ["upper_abs", "lower_abs"]},
    # Cardio
    {"id": "run",         "name": "Running",               "category": "Cardio",    "type": "cardio",   "description": "Steady-state running for general aerobic conditioning and lower-body endurance.", "primary_muscles": ["gastroc", "quad_rf"],                                  "secondary_muscles": ["ham_bf", "glute_max", "soleus"]},
    {"id": "cycle",       "name": "Cycling",               "category": "Cardio",    "type": "cardio",   "description": "Low-impact stationary or outdoor cycling for cardio and quad endurance.", "primary_muscles": ["quad_rf", "quad_vl"],                                  "secondary_muscles": ["ham_bf", "gastroc", "glute_max"]},
    {"id": "row_erg",     "name": "Rowing Erg",            "category": "Cardio",    "type": "cardio",   "description": "Indoor rowing — full-body cardio that trains the legs, back, and arms in a 1:2 drive-to-recovery rhythm.", "primary_muscles": ["lower_lat", "rhomboid"],                               "secondary_muscles": ["quad_rf", "ham_bf", "erector", "bicep_long"]},
    {"id": "jump_rope",   "name": "Jump Rope",             "category": "Cardio",    "type": "cardio",   "description": "Wrist-driven rope skipping for fast-twitch conditioning and calf endurance.", "primary_muscles": ["gastroc", "soleus"],                                   "secondary_muscles": ["quad_rf", "ham_bf"]},
    {"id": "stair",       "name": "Stair Climber",         "category": "Cardio",    "type": "cardio",   "description": "Continuous stair-climbing machine — quad and glute focused steady-state cardio.", "primary_muscles": ["quad_rf", "glute_max"],                                "secondary_muscles": ["ham_bf", "gastroc"]},
    {"id": "assault",     "name": "Assault Bike",          "category": "Cardio",    "type": "cardio",   "description": "Fan bike with moving arm levers — brutal full-body cardio with no upper limit on intensity.", "primary_muscles": ["gastroc", "quad_rf"],                                  "secondary_muscles": ["ham_bf", "glute_max"]},
    {"id": "swim",        "name": "Swimming",              "category": "Cardio",    "type": "cardio",   "description": "Low-impact full-body conditioning that hammers the lats, delts, and respiratory system.", "primary_muscles": ["upper_lat", "front_delt"],                             "secondary_muscles": ["teres_major", "tricep_long", "rear_delt"]},
    {"id": "sled_push",   "name": "Sled Push",             "category": "Cardio",    "type": "cardio",   "description": "Heavy push of a weighted sled — concentric-only conditioning that builds leg drive without soreness.", "primary_muscles": ["quad_rf", "glute_max"],                               "secondary_muscles": ["ham_bf", "gastroc", "erector"]},
    {"id": "battle_rope", "name": "Battle Ropes",          "category": "Cardio",    "type": "cardio",   "description": "Heavy rope waves and slams — short, high-intensity intervals for shoulders, grip, and lungs.", "primary_muscles": ["front_delt", "side_delt"],                             "secondary_muscles": ["upper_abs", "lower_abs", "oblique"]},
    {"id": "hiit",        "name": "HIIT",                  "category": "Cardio",    "type": "cardio",   "description": "High-intensity interval training: short max-effort bouts with brief rests for cardiovascular and metabolic conditioning.", "primary_muscles": ["quad_rf", "gastroc"],                                  "secondary_muscles": ["ham_bf", "glute_max", "upper_abs"]},
]


def seed(db=None):
    """Idempotent seed: insert any missing exercises and backfill descriptions on
    existing rows whose `description` is still empty. Pre-existing exercise rows
    keep all of their other fields untouched so admin edits survive a re-seed."""
    own_session = db is None
    if own_session:
        db = SessionLocal()
    try:
        inserted = 0
        backfilled = 0
        for ex_data in EXERCISES:
            existing = db.query(models.Exercise).filter(models.Exercise.id == ex_data["id"]).first()
            if existing is None:
                db.add(models.Exercise(**ex_data))
                inserted += 1
            else:
                if not existing.description and ex_data.get("description"):
                    existing.description = ex_data["description"]
                    backfilled += 1
        db.commit()
        print(
            f"Seeded {inserted} new exercises, backfilled descriptions on {backfilled} existing rows."
        )
    finally:
        if own_session:
            db.close()


if __name__ == "__main__":
    seed()
